# Generated by Django 4.0.4 on 2022-08-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер заказа')),
                ('total_dollar', models.FloatField(verbose_name='Сумма в долларах')),
                ('supply', models.DateField(verbose_name='Срок поставки')),
                ('total_rub', models.FloatField(verbose_name='Сумма в рублях')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
